name: Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  semantic_release:
    name: "Semantic Release"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm init --yes
      - run: npm install semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec conventional-changelog-conventionalcommits --save-dev
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}